home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('forget-password', views.forget_password_view, name='forget-password'),
    path('new-password', views.new_password_view, name='new-password'),
    path('change-password', views.change_password_view, name='change-password'),
    path('user-task', views.user_task_view, name='user-task'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_management_api/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', include('home.urls', namespace='home')),
    path('api/', include('project_api.urls')),
]

projects/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'projects'

urlpatterns = [
    path('',views.projects, name='projects'),
    path('new-project/',views.newProject, name='new-project'),
    path('new-task/',views.newTask, name='new-task'),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('new-user/', views.register, name='new-user'),
    path('new-company/', views.newCompany, name='new-company'),
    path('users/', views.usersView, name='users'),
    path('users/profile', views.profile, name='profile'),
    path('users/<int:profile_id>/', views.user_view, name='user'),
    path('users/invite/<int:profile_id>/', views.invite, name='invite'),
    path('users/invites/', views.invites, name='invites'),
    path('users/invites/accept/<int:invite_id>/', views.acceptInvite, name='accept-invite'),
    path('users/invites/delete/<int:invite_id>/', views.deleteInvite, name='delete-invite'),
    path('users/friends/', views.friends, name='friends'),
    path('users/friends/remove/<int:profile_id>/', views.remove_friend, name='remove-friend'),
    
]

home/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


"""These are defined for the project status in a list"""

status = (
    ('1','Stuck'),
    ('2','Working'),
    ('3', 'Done'),
)

due = (
    ('1', 'On Due'),
    ('2', 'Overdue'),
    ('3', 'Done'),
)

class Project(models.Model):
    """Creating Database table for Project"""


    name = models.CharField(max_length=80)
    slug = models.SlugField('shortcut', blank=True)
    assign = models.ManyToManyField(User)
    efforts = models.DurationField()
    status = models.CharField(max_length=7, choices=status, default=1)
    dead_line = models.DateField()
    company = models.ForeignKey('register.Company', on_delete=models.CASCADE)
    complete_per = models.FloatField(max_length=2, validators = [MinValueValidator(0), MaxValueValidator(100)])
    description = models.TextField(blank=True)

    add_date = models.DateField(auto_now_add=True)
    upd_date = models.DateField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        """Returing name of the project to display"""

        return (self.name)


class Task(models.Model):
    """This class is created for the task table in database"""


    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    assign = models.ManyToManyField(User)
    task_name = models.CharField(max_length=80)
    status = models.CharField(max_length=7, choices=status, default=1)
    due = models.CharField(max_length=7, choices=due, default=1)

    class Meta:
        ordering = ['project', 'task_name']

    def __str__(self):
        """Returning the task name to display"""

        return(self.task_name)

home/views.py
from ast import Assign
from asyncio import tasks
from distutils.log import error
from tokenize import group
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from register.models import Company
from register.models import Project
from register.models import UserProfile
from projects.models import Task
import psutil, os
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.hashers import make_password





def index(request):
    """ Function to display index """

    projects = Project.objects.all()
    return render(request, 'core/index.html',{'projects':projects})


def dashboard(request):
    """ Function to display dashboard of the website """

    users = User.objects.all()
    active_users = User.objects.all().filter(is_active=True)
    companies = Company.objects.all()
    projects = Project.objects.all()
    tasks = Task.objects.all()
    cup_usage = psutil.cpu_percent(4)
    #print('jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj',cup_usage)
    context = {
        'users' : users,
        'active_users' : active_users,
        'companies' : companies,
        'projects' : projects,
        'tasks' : tasks,
        'cpu_usage':cup_usage,
    }
    return render(request, 'core/dashboard.html', context)


def login_view(request):
    """ Function to login user """

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            authenticated_user = authenticate(username=request.POST['username'], password=request.POST['password'])
            login(request, authenticated_user)
            return redirect('home:index')
        else:
            return render(request, 'register/login.html', {'login_form':form})
    else:
        form = AuthenticationForm()
    return render(request, 'register/login.html', {'login_form':form})


def logout_view(request):
    """ Function to logout user """

    logout(request)
    return HttpResponseRedirect(reverse('home:index'))


def forget_password_view(request):
    """ Function to check username and redirect to password reset page """

    if request.method == "POST":
        username = request.POST.get('username')
        try:
            user = User.objects.get(username = username)
        except ObjectDoesNotExist:
            messages.warning(request, 'Please Create your account first !!!')
            return render(request, 'register/forget_password.html')
        if user:
            if username == user.username:
                request.session['user'] = user.id
                return redirect('home:new-password')
            else:
                messages.info(request, 'Username not found !!!')
                return render(request, 'register/forget_password.html')
        else:
            messages.info(request, 'Username not found !!!')
    return render(request, 'register/forget_password.html')


def new_password_view(request):
    """ Function to reset new password """

    u_id = request.session['user']
    user = User.objects.get(id = u_id)

    if request.method == "POST":
        pwd = request.POST.get('new_password')
        c_pwd = request.POST['con_pass']
        error_message = None
        if pwd == c_pwd:
            enccrypt_pwd = make_password(pwd)
            user.password = enccrypt_pwd
            user.save()
            messages.success(request, 'Password Reset Successfully.')
            return redirect('home:index')
        else:
            messages.warning(request, 'Password does not match')
            return redirect('home:new-password')
    return render(request, 'register/new_password.html')


def context(request): # send context to base.html
    # if not request.session.session_key:
    #     request.session.create()
    users = User.objects.all()
    users_prof = UserProfile.objects.all()
    if request.user.is_authenticated:
        try:
            users_prof = UserProfile.objects.exclude(
                id=request.user.userprofile_set.values_list()[0][0])  # exclude himself from invite list
            user_id = request.user.userprofile_set.values_list()[0][0]
            logged_user = UserProfile.objects.get(id=user_id)
            friends = logged_user.friends.all()
            context = {
                'users': users,
                'users_prof': users_prof,
                'logged_user': logged_user,
                'friends' : friends,
            }
            return context
        except:
            users_prof = UserProfile.objects.all()
            context = {
                'users':users,
                'users_prof':users_prof,
            }
            return context
    else:
        context = {
            'users': users,
            'users_prof': users_prof,
        }
        return context


@login_required
def change_password_view(request):
    """ Function to change password of logedin user """

    if request.user.is_authenticated:
        if request.method == 'POST':
            old_password = request.POST['old_password']
            new_password = request.POST['new_password']
            con_pass = request.POST['con_pass']
            if new_password == con_pass:
                user = authenticate(request, username= request.user, password = old_password)
                if user is not None:
                    user = User.objects.get(username = request.user.username)
                    user.set_password(new_password)
                    user.is_visit = True
                    user.save()
                    messages.success(request, "Password Has Been Changed")
                    return redirect('home:index')
                else:
                    messages.warning(request, "Old password not match !!!")
                    return redirect('home:change-password')
            else:
                messages.warning(request, "Password does not match")
                return redirect('home:change-password')
        else:
            # messages.success(request, "Something went wrong !!!")
            return render(request, 'register/change_password.html')
    else:
        return render(request, 'register/change_password.html')
    

def user_task_view(request):
    """ Function to show the assigned task of logged in user """
    
    u_id = request.user.id
    task_details = Task.objects.all()
    projects = Project.objects.all()
    user_task = Task.objects.filter(assign = u_id)
    context = {
        'projects' : projects,
        'user_task' : user_task,
    }

    print('current user id : ', u_id)
    print('Task assigned to user : ',user_task)
    if request.user.is_authenticated:
        return render(request, 'core/user_task.html',context)
    else:
        return render(request, 'core/index.html')

home/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-147225311-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-147225311-2');
    </script>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
  <meta name="author" content="Łukasz Holeczek">
  <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,AngularJS,Angular,Angular2,Angular 2,Angular4,Angular 4,jQuery,CSS,HTML,RWD,Dashboard,React,React.js,Vue,Vue.js">
  <meta name="google-site-verification" content="83fcqoPn-YTkXathQiicW-x3U2RWZh4PaPUzk91wtjY" />
  <title>Project System</title>

  <!-- Icons -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">
  <link href="{% static 'core/css/simple-line-icons.min.css' %}" rel="stylesheet">

  <!-- Main styles for this application -->
  <link href="{% static 'core/css/estilo.css' %}" rel="stylesheet">
  <link href="{% static 'core/css/style.css' %}" rel="stylesheet">

</head>
{% block body %}
<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">

  <header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <img src="{% static 'core/img/logos/title.png' %}" alt="" class="brand-gui ml-2 d-none d-sm-block p-2">
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav d-md-down-none">
      <li class="nav-item px-3">
        <a class="nav-link" href="{% url 'home:index' %}">Home</a>
      </li>
      <li class="nav-item px-3">
        <a class="nav-link" href="{% url 'home:dashboard' %}">Dashboard</a>
      </li>
      <!--<li class="nav-item px-3">-->
        <!--<a class="nav-link" href="#">Settings</a>-->
      <!--</li>-->
    </ul>
    <ul class="nav navbar-nav ml-auto">
      <li class="nav-item d-md-down-none">
        <a class="nav-link" href="#"><i class="fa fa-bell"></i><span class="badge badge-pill badge-danger">{{ logged_user.received_invites.count }}</span></a>
      </li>
      <li class="nav-item d-md-down-none">
        <a class="nav-link" href="#"><i class="fa fa-list"></i></a>
      </li>
      <li class="nav-item d-md-down-none">
        <a class="nav-link" href="#"><i class="fa fa-map-marker"></i></a>
      </li>
      {% if user.is_authenticated %}
      <li class="text-muted">Hello, {{ user.first_name }}</li>
      {% else %}
      <li class="text-muted">
        <a href="{% url 'home:login' %}">sign in</a>
      </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          {% if user.is_authenticated %}
          <img src="{{ logged_user.img.url }}" class="img-avatar" alt="{{ user }}">
          {% else %}
          <img src="{% static 'core/img/avatar/blank_profile.png' %}" class="img-avatar" alt="{{ user }}">
          {% endif %}
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="dropdown-header text-center">
            <strong>Account</strong>
          </div>
          {% if user.is_authenticated %}
          <!--<a class="dropdown-item" href="#"><i class="fa fa-bell-o"></i> Updates<span class="badge badge-info">42</span></a>-->
          <a class="dropdown-item" href="{% url 'register:invites' %}"><i class="fa fa-envelope-o"></i> Invites<span class="badge badge-success">{{ logged_user.received_invites.count }}</span></a>
          <a class="dropdown-item" href="{% url 'home:user-task' %}"><i class="fa fa-tasks"></i> Tasks<span class="badge badge-danger">{{ user.task_set.values.count }}</span></a>
          <!--<a class="dropdown-item" href="#"><i class="fa fa-comments"></i> Comments<span class="badge badge-warning">42</span></a>-->
          <div class="dropdown-header text-center">
            <strong>Settings</strong>
          </div>
          {% if user.is_superuser %}
          {% else %}
          <a class="dropdown-item" href="{% url 'register:profile' %}"><i class="fa fa-user"></i> Profile</a>
          {%endif%}
          <a class="dropdown-item" href="{% url 'home:change-password' %}"><i class="fa fa-asterisk"></i> Change Password</a>
          <!-- <a class="dropdown-item" href="#"><i class="fa fa-usd"></i> Payments<span class="badge badge-secondary">42</span></a> -->
          <a class="dropdown-item" href="{% url 'projects:projects'%}"><i class="fa fa-file"></i> Projects<span class="badge badge-primary">{{projects.count}}</span></a>
          <div class="divider"></div>
          <!--<a class="dropdown-item" href="#"><i class="fa fa-shield"></i> Lock Account</a>-->

          <a class="dropdown-item" href="{% url 'home:logout' %}"><i class="fa fa-lock"></i> Logout</a>
          {% else %}
          <a class="dropdown-item" href="{% url 'home:login' %}"><i class="fa fa-user"></i> Login</a>
          {% endif %}
        </div>
      </li>
    </ul>
    <button class="navbar-toggler aside-menu-toggler" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>

  </header>

  <div class="app-body">
    <div class="sidebar">
      <nav class="sidebar-nav">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:index' %}"><i class="fa fa-home"></i> Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:dashboard' %}"><i class="fa fa-tachometer-alt"></i> Dashboard</a>
          </li>
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-tachometer-alt"></i> Views</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'projects:projects'%}"><i class="fa fa-paper-plane ml-2"></i> Project's View</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register:users'%}"><i class="fa fa-user ml-2"></i> Users Views</a>
              </li>
            </ul>
          </li>

          <!--<li class="nav-title">-->
            <!--Theme-->
          <!--</li>-->
          <!--<li class="nav-item">-->
            <!--<a href="colors.html" class="nav-link"><i class="fa fa-tint"></i> Colors</a>-->
          <!--</li>-->
          <!--<li class="nav-item">-->
            <!--<a href="typography.html" class="nav-link"><i class="fa fa-user"></i> Typograhy</a>-->
          <!--</li>-->
          <li class="nav-title">
            Register
          </li>
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-industry"></i> Company</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register:new-company'%}"><i class="fa fa-plus ml-2"></i> New Company</a>
              </li>
            </ul>
          </li>
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-puzzle-piece"></i> Projects</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'projects:new-project'%}"><i class="fa fa-plus ml-2"></i> New Project</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'projects:new-task'%}"><i class="fa fa-plus ml-2"></i> New Task</a>
              </li>
            </ul>
          </li>
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-user"></i> Users</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register:new-user' %}"><i class="fa fa-user-plus ml-2"></i> Create New User</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register:friends' %}"><i class="fa fa-users ml-2"></i> Friends</a>
              </li>
            </ul>
          </li>
          <li class="divider"></li>
          <li class="nav-title">
            Extras
          </li>
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-star"></i> Pages</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:login' %}" target="_top"><i class="fa fa-sign-in"></i> Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:logout' %}" target="_top"><i class="fa fa-sign-out"></i> Logout</a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <button class="sidebar-minimizer brand-minimizer" type="button"></button>
    </div>

    <!-- Main content -->
    <main class="main">
      <!-- Breadcrumb -->
      <ol class="breadcrumb">
        {% block breadcrumb %}
        <li class="breadcrumb-item active">Home</li>
        <li class="breadcrumb-item">Dashboard</li>
        {% endblock breadcrumb%}

        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
          <div class="btn-group" role="group" aria-label="Button group">
            <!-- <a class="btn" href="#"><i class="fa fa-comments"></i></a> -->
            <a class="btn" href="./"><i class="fa fa-tachometer-alt"></i> &nbsp;Dashboard</a>
            <!-- <a class="btn" href="#"><i class="fa fa-cog"></i> &nbsp;Settings</a> -->
          </div>
        </li>
      </ol>
{% block content %}
{% endblock %}
    </main>

    <aside class="aside-menu">

      <!-- Tab panes -->
      <div class="tab-content">
        <div class="tab-pane active" id="timeline" role="tabpanel">
          {% if user.is_authenticated %}
          <div class="callout m-0 py-2 text-muted text-center bg-light text-uppercase">
            <small><b>Suggested Friends</b></small>
          </div>
          {% for user in users_prof %}
          {% if not user in friends %}
          <div class="m-2 mt-4 float-left">
              <div class="avatar">
                <img src="{{ user.img.url }}" class="img-avatar" alt="{{ user.user.get_full_name }}">
                <span class="avatar-status badge-success"></span>
              </div>
          </div>
          <hr class="transparent mx-3 my-0">
          <hr class="mx-3 my-0">
          <div class="callout callout-success m-0 py-3">
            <div>
              <a href="{% url 'register:user' profile_id=user.id %}" class="text-dark">{{ user.user.first_name }} {{ user.user.last_name }}</a>
            </div>
              {% if user.user.last_login %}
              <small class="text-muted mr-3">Last login: {{ user.user.last_login|date:"H:i" }} in {{ user.user.last_login|date:"d/m" }}</small>
              {% else %}
              <small class="text-muted mr-3">Never logged in</small>
              {% endif %}
            <small class="text-muted text-truncate"><i class="fa fa-industry"></i> {{ user.company }}</small>
            <a href="{% url 'register:invite' profile_id=user.id %}" class="badge badge-success text-white">Send Invite</a>
          </div>
          {% else %}
          {% endif %}
          {% endfor %}
          {% else %}
          <div class="callout m-0 py-2 text-muted text-center bg-light text-uppercase">
            <small><b>Suggested Friends</b></small>
          </div>
          <div class="callout callout-success m-0 py-3">
            <div>
              <strong></strong></div>

            <small class="text-muted text-truncate">Log in to see your Friends Suggested List</small>
            <a href="{% url 'home:login' %}" class="badge badge-success text-white">Log in</a>
          </div>
          {% endif %}
        </div>
        
      </div>
    </aside>

  </div>

  <footer class="app-footer">
    <span><a href="http://coreui.io">Copyright</a> © 2022 Django API- Project Management.</span>
    <!--<span class="ml-auto">Powered by <a href="http://coreui.io">CoreUI</a></span>-->
  </footer>

  <!-- Bootstrap and necessary plugins -->
    <script src="{% static 'core/vendors/js/jquery.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/popper.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/pace.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/Chart.min.js'%}"></script>

  <!-- CoreUI main scripts -->

    <script src="{% static 'core/js/app.js'%}"></script>

  <!-- Plugins and scripts required by this views -->

  <!-- Custom scripts required by this view -->
    <script src="{% static 'core/js/main.js'%}"></script>
    

</body>
{% endblock body %}
</html>

home/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block breadcrumb %}
<li class="breadcrumb-item active">Home</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid">
  <div id="ui-view" style="opacity: 1;"><div class="animated fadeIn">
    <div class="row">
    <div class="col-12">
      <div class="card">
      <div class="card-header">
        <i class="fa fa-align-justify"></i> Main info
        <div class="card-actions">
          <!-- <a href="" target="_blank">
            <small class="text-muted">docs</small>
          </a> -->
        </div>
      </div>
      <div class="card-body">
        <div class="jumbotron bg-white">
          <h1 class="display-4">LaNet Software Solution Pvt.Ltd.</h1>
          <p class="lead">Welcome to the Project Management System.</p>
          <hr class="my-4">
          <div>
            <img src="{% static 'core/img/avatar/pm.jpg' %}" width="auto" class="img-fluid" alt="Responsive image">
          </div>
          <p>Register your company and start managing your projects</p>
          <p>That's it, simple, easy, fast.</p>
          <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'register:new-company' %}" role="button">Set up your company</a>
          </p>
          {% if not user.is_authenticated %}
          <a href="{% url 'home:login' %}">Click here if you are already registered</a>
          {% endif %}
        </div>
      </div>
      </div>
    </div>
    </div>
    </div>
  </div>
</div>

{% endblock %}

home/templates/core/user_task.html
{% extends 'core/base.html' %}
{% load static %}

{% block breadcrumb %}
<li class="breadcrumb-item active">Home</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid">
  <div id="ui-view" style="opacity: 1;"><div class="animated fadeIn">
    <div class="row">
    <div class="col-12">
      <div class="card">
      <div class="card-header">
        <i class="fa fa-align-justify"></i> Task Assign To - {{user.username}}
        <div class="card-actions">
          <!-- <a href="" target="_blank">
            <small class="text-muted">docs</small>
          </a> -->
        </div>
      </div>
      <div class="card-body">
        <div class="jumbotron bg-white">
          <!-- <h1 class="display-4">LaNet Software Solution Pvt.Ltd.</h1>
          <p class="lead">Welcome to the Project Management System.</p>
          <hr class="my-4"> -->
          <div>
            <img src="{% static 'core/img/avatar/pm.jpg' %}" width="auto" class="img-fluid" alt="Responsive image">
          </div>
          <!-- <p>Register your company and start managing your projects</p>
          <p>That's it, simple, easy, fast.</p>
          <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'register:new-company' %}" role="button">Set up your company</a>
          </p>
          {% if not user.is_authenticated %}
          <a href="{% url 'home:login' %}">Click here if you are already registered</a>
          {% endif %} -->
          <h3 class="display-5 text-center m-5">Task Lists Assigned To You {{user.first_name}}</h3>
          <table class="table table-hover">
            <thead>
              <tr style="background-color: orange;">
                <th scope="col">S.N</th>
                <th scope="col">Project Name</th>
                <th scope="col">Task Name</th>
                <th scope="col">Status</th>
                <th scope="col">Due</th>
              </tr>
            </thead>
            <tbody>
                {% for task in user_task %}
              <tr>
                <th class="h6" scope="row">{{forloop.counter}}</th>
                <td class="h6">{{task.project.name}}</td>
                <td class="h6">{{task.task_name}}</td>
                <td class="h6">{{task.get_status_display}}</td>
                <td class="h6">{{task.get_due_display}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      </div>
    </div>
    </div>
    </div>
  </div>
</div>

{% endblock %}